// Astro wrapper components

// Re-export everything from core so Astro consumers get full API
export {
  allBundledThemes,
  applyThemeColors,
  clearThemeColors,
  defaultThemes,
  filterThemesByPreset,
  generateThemeCSS,
  generateThemeInitScript,
  generateThemeStylesheet,
  getFamilyIds,
  groupByFamily,
  initTheme,
  kawaiiThemes,
  lessIsMoreThemes,
  registerAll,
  registerThemeController,
  registerThemePreview,
  registerThemeToggle,
  resolveAxes,
  resolveTheme,
  seventiesThemes,
  ThemeControllerElement,
  type ThemeInitScriptOptions,
  ThemePreviewElement,
  ThemeToggleElement,
  themeContrast,
  themeInitScript,
  themeVariation,
} from "../core/index";
// Re-export types
// Deprecated aliases
export type {
  ColorToken,
  ThemeApplyMode,
  ThemeAxis,
  ThemeCategory,
  ThemeColors,
  ThemeConfig,
  ThemeContrast,
  ThemeControllerProps,
  ThemeFamily,
  ThemeIcon,
  ThemeMode,
  ThemePreset,
  ThemeScheme,
  ToggleApplyMode,
} from "../types";
